from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from time import sleep
servico = Service(ChromeDriverManager().install())
navegador = webdriver.Chrome(service=servico)

navegador.get('http://127.0.0.1:8000/')
navegador.find_element('xpath','/html/body/nav/div[2]/a[4]').click()
sleep(3)
navegador.find_element('xpath', '/html/body/form/div/span[1]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[2]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[3]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[4]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[5]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[6]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[7]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[8]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[9]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath', '/html/body/form/div/span[10]/input').send_keys("10")
sleep(1)
navegador.find_element('xpath','/html/body/form/div/input').click()
sleep(1)