# Generated by Django 5.0.dev20230402075433 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email@default.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='12345678', max_length=25),
        ),
    ]
