# Generated by Django 4.2 on 2023-05-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0009_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
