# Generated by Django 4.2 on 2023-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0011_rename_quantidade_ml_registro_agua_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro_Agua',
        ),
    ]
