# Generated by Django 4.2 on 2023-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0012_agua_delete_registro_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agua',
            name='data',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='agua',
            name='hora',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
