# Generated by Django 4.2 on 2023-05-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0014_cadastro_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comentario_Antebraco_rosca_inversa_punho_dumbell',
        ),
    ]
