# Generated by Django 4.2 on 2023-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0005_user_delete_usuario_rename_coment_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peito', models.DecimalField(decimal_places=2, max_digits=3)),
                ('costas', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ombro', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pescoco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('braco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('antebraco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coxa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('panturrilha', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
