# Generated by Django 4.2 on 2023-05-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0010_delete_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_agua',
            old_name='quantidade_ml',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='data',
        ),
    ]
