# Generated by Django 4.2 on 2023-05-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FullBA', '0016_comentario_antebraco_rosca_punho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_antebraco_rosca_inversa_punho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_antebraco_rosca_punho_cross_over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
    ]
